config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
  root to:'homes#top'
  get 'home/about' => 'homes#about',as: 'homes_about'
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resources :books, only:[:new, :create, :index, :show, :edit,:destroy, :update] do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end
  resources :users, only:[:index, :show, :edit, :update]
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  post 'followings/:id' => 'relationships#followings', as: 'followings'
  post 'followers/:id' => 'relationships#followers', as: 'followers'
  get 'search' => 'searches#search', as: 'search'
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence:true
  validates :body, presence:true, length:{maximum:200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backword_match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}")
    else
      @book = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence:true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # ユーザーとフォローする人、される人を関連付け
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローしてる人、されてる人の一覧
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_id, through: :followed, source: :follower
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  attachment :profile_image

  validates :name, presence:true, uniqueness:true, length:{minimum:2, maximum:20}
  validates :introduction, length:{maximum:50}

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  # フォローしているか確認
  def following?(user)
    following_user.include?(user)
  end

  # 検索方法条件分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backword_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

  # 住所自動入力
  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    @user = current_user
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      @user = current_user
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    if user_rooms.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: @user.id, room_id: @room.id)
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
    else
      @room = user_rooms.room
    end

    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end

  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @user = current_user
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @newbook = Book.new
    @user = current_user
    @users = User.all
  end

  def show
    @newbook = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <p>
    <%= link_to book_favorites_path(book), method: :delete,remote: true, class:'text-danger' do %>
      ♥<%= book.favorites.count %>
    <% end %>
  </p>
<% else %>
  <p>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      ♥<%= book.favorites.count %>
    <% end %>
  </p>
<% end %>

app/views/books/_userinfo.html.erb
      <!--user info-->
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpg',fallback: "person.jpg", size:"100x100" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th>
              <%= link_to followings_path(user.id), method: :post do %>
                <%= user.following_user.count %>
              <% end %>
            </th>
          </tr>
          <tr>
            <th>followers</th>
            <th>
              <%= link_to followers_path(user.id), method: :post do %>
                <%= user.follower_id.count %>
              <% end %>
            </th>
          </tr>
        </tbody>
      </table>
      <% unless user == current_user %>
        <% if current_user.following?(user) %>
          <%= link_to "フォロー外す", unfollow_path(user.id), method: :dpost, class:'btn btn-primary mb-2' %>
        <% else %>
          <%= link_to "フォローする", follow_path, method: :post, class:'btn btn-success mb-2' %>
        <% end %>
        <br>
        <%= link_to 'チャットする', chat_path(user.id), class:'btn btn-warning' %>
      <% else %>
        <div class="row">
          <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
            <span class="fas fa-user-cog"></span>
          <% end %>
        </div>
      <% end %>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book, local:true do |f| %>
        <div class="form-group">
          <%= f.label :title, "Title" %>
          <%= f.text_field :title, class:"form-control book_title" %>
        </div>
        <div class="form-group">
          <%= f.label :body, "Opinion" %>
          <%= f.text_area :body, class:"form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Book", class:"btn btn-success" %>
        </div>
      <% end %>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <div class="error-explanation">
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <%= f.label :title, "Title" %>
          <%= f.text_field :title, class:"form-control book_title" %>
        </div>
        <div class="form-group">
          <%= f.label :body, "Opinion" %>
          <%= f.text_area :body, class:"form-control book_title" %>
        </div>
        <div class="form-group">
           <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="error-explanation">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-3">
      <!--useeinfo部分テンプレート-->
      <%= render 'books/userinfo',user: @user, book: @book %>
    </div>
    <!--books-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpg',fallback: "person.jpg", size:"40x40"%>
              <% end %>
              </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
              </td>
            <td><%= book.body %></td>
            <td class="book-<%= book.id %>">
              <%= render 'books/favorite',book: book %>
            </td>
            <td>
              <p>
                コメント数：<%= book.book_comments.count %>
              </p>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
       <!--useeinfo部分テンプレート-->
      <%= render 'books/userinfo', user: @user, book: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpg',fallback: "person.jpg", size:"40x40"%>
                <br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td><%= @book.body %></td>
            <td class="book-<%= @book.id %>"><%= render 'books/favorite', book: @book %></td>
            <td class="comments-count">
              <p>
                コメント数：<%= @book.book_comments.count %>
              </p>
            </td>
            <% if @book.user.id == current_user.id %>
              <td>
                <%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-sm btn-success" %>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか?", class:"btn btn-sm btn-danger" %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>

        <%= render 'book_comments/comments', book: @book, book_comment: @book_comment %>

      <div class="comment-form">
         <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
      </div>
    </div>
  </div>
</div>

app/views/chats/create.js.erb
$('.chats').append("<p><%= @chat.message %></p>");
$("input[type=text]").val('')

app/views/chats/show.html.erb
<div class="container">
  <div class="row">
    <h2><%= @user.name %>さんとのチャット</h2>
    <table class="chats table">
      <thead>
        <tr>
          <td>投稿内容</td>
        </tr>
      </thead>
      <tbody>
        <% @chats.each do |chat| %>
          <tr>
            <td>
              <p><%= chat.message %></p>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= form_with model: @chat do |f| %>
      <%= f.text_field :message %>
      <%= f.hidden_field :room_id %>
    <% end %>
  </div>
</div>